name: unit_test

on: [push]
# merging pull request results in a push, hence pull_request events might be ignored
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  unit_test:
    # runs-on: ubuntu-latest
    # Need >= 20.04 for modern sqlite.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: spherex_butler_poc

      - name: Checkout daf_butler
        uses: actions/checkout@v2
        with:
          repository: lsst/daf_butler
          path: daf_butler

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install sqlite
        run: sudo apt-get install sqlite libyaml-dev

      - name: Install dax_butler dependencies
        run: pip install -r https://raw.githubusercontent.com/lsst/daf_butler/master/requirements.txt

      # pytest-xdist allows to parallelize testing on multiple CPUs
      # pytest-openfiles allows to detect open I/O resources at the end of unit tests
      - name: Install pytest packages
        run: pip install pytest pytest-flake8 pytest-xdist pytest-openfiles

      - name: Build and install
        run: |
          cd ${{ github.workspace }}/daf_butler
          pip install -v .
          cd ${{ github.workspace }}/spherex_butler_poc
          pip install -v .

      # "-r char" show extra test info for some tests, A - all
      # "-n auto" to use as many processes as your computer has CPU cores
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/spherex_butler_poc

          pytest --ignore python/spherex/tasks/ -r A -v -n auto --open-files

